server:
  port: 8081

spring:
  application:
    name: im-client

dubbo:
  application:
    qos-enable: false
    name: ${spring.application.name}
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20881

im-client:
  health:
    heart-beat:
      client-to-server-s: 10