server:
  port: 8081
  servlet:
    context-path: /im-client

spring:
  application:
    name: im-client
  main:
    allow-circular-references: true

dubbo:
  application:
    qos-enable: false
    name: ${spring.application.name}
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20881
    serialization: hessian2
  consumer:
    check: false
    retries: 0

im-client:
  health:
    heart-beat:
      client-to-server-s: 10