server:
  port: 8083

spring:
  application:
    name: im-server

im-server:
  im-port: 9527
  health:
    heart-beat:
      client-to-server-s: 11
  registry:
    zk:
      host: 127.0.0.1
      port: 2181
      root: /im-peers