server:
  port: 8082

spring:
  application:
    name: im-mgr

dubbo:
  application:
    qos-enable: false
    name: ${spring.application.name}
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20882