server:
  port: 8082

spring:
  main:
    allow-circular-references: true
  application:
    name: im-mgr
  datasource:
    url: jdbc:mysql://localhost:3306/im-sys?allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: dingrui19920308
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
  cache:
    type: redis

dubbo:
  application:
    qos-enable: false
    name: ${spring.application.name}
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20882
    serialization: hessian2

mybatis-plus:
  configuration:
    cache-enabled: false
    use-generated-keys: true
    default-executor-type: REUSE
    use-actual-param-name: true

im-mgr:
  im-server:
    registry:
      # 服务器注册在zk的信息
      zk:
        host: 127.0.0.1
        port: 2181
        root: /im-peers